apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kurtb/localflow.git
    targetRevision: HEAD
    path: apps
  destination:
    name: default
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true